version: '3'

volumes:
  cache:
    driver: local
  db-data:
    driver: local

services:
  app:
    build:
      context: .
    container_name: technicalTask
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - '8080:8080'

  db:
    image: postgres:15.0-alpine
    container_name: postgres
    ports:
      - '5401:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    restart: unless-stopped

  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data